# Generated by Django 6.1.1 on 2026-09-16 21:35

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='IngredientLifespan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_category', models.CharField(max_length=120)),
                ('storage_zone', models.CharField(choices=[('fridge', 'Fridge'), ('freezer', 'Freezer'), ('pantry', 'Pantry'), ('counter', 'Counter')], max_length=20)),
                ('package_state', models.CharField(choices=[('unopened', 'Unopened'), ('opened', 'Opened'), ('thawed', 'Thawed')], default='unopened', max_length=20)),
                ('typical_days', models.PositiveIntegerField(help_text='Typical days until the item should be used.')),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'ingredient_lifespans',
                'ordering': ['food_category', 'storage_zone', 'package_state'],
                'constraints': [models.UniqueConstraint(fields=('food_category', 'storage_zone', 'package_state'), name='unique_lifespan_lookup')],
            },
        ),
        migrations.CreateModel(
            name='Pantry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('barcode', models.CharField(blank=True, max_length=64)),
                ('food_category', models.CharField(blank=True, max_length=120)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=40)),
                ('storage_zone', models.CharField(choices=[('fridge', 'Fridge'), ('freezer', 'Freezer'), ('pantry', 'Pantry'), ('counter', 'Counter')], default='pantry', max_length=20)),
                ('package_state', models.CharField(choices=[('unopened', 'Unopened'), ('opened', 'Opened'), ('thawed', 'Thawed')], default='unopened', max_length=20)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('used_up', 'Used up'), ('thrown_out', 'Thrown out')], default='active', max_length=20)),
                ('is_staple', models.BooleanField(default=False, help_text='Assume on hand unless marked empty.')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lifespan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pantry_items', to='api.ingredientlifespan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pantry_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'pantry items',
                'db_table': 'pantry',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('servings', models.PositiveIntegerField(default=1)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags such as weeknight, batch, leftovers.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recipes',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=40)),
                ('food_category', models.CharField(blank=True, max_length=120)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='api.recipe')),
            ],
            options={
                'db_table': 'recipe_ingredients',
                'ordering': ['id'],
            },
        ),
    ]
