# Generated by Django 6.1.1 on 2026-09-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='food_category',
        ),
        migrations.RemoveField(
            model_name='user',
            name='timezone',
        ),
        migrations.AlterField(
            model_name='ingredientlifespan',
            name='typical_days',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pantry',
            name='is_staple',
            field=models.BooleanField(default=False),
        ),
    ]
